### PR TITLE
Fix "Compatibility Wrapper" object docs written to wrong part of tree

### LINKED ISSUE #430: [Bug]: "Compatibility Wrapper" object docs written to wrong part of tree
### Current Behavior:

PlanSecurity* transaction markdown is being written to `docs/schema_markdown/PlanSecurity*.md` instead of `docs/schema_markdown/schema/objects/transactions/*/PlanSecurity*.md`. This _may_ only happen on releases for some reason.

### Expected Behavior:

Markdown should be written to the same paths as other txns.

### Steps to Reproduce:
Feel free to replace `1.1.0` with some other fake release version.

```
node --loader ts-node/esm --no-warnings --experimental-json-modules ./utils/schema-utils/EnforceCopyrightNotices.ts check-notices -fvart --tag v1.1.0 && git add schema utils

# updates ids and refs
npm run generate-release-docs 1.1.0 && git add schema utils

# manually update enums
# search and replace all JSON files replacing manifest version with "1.1.0"

# generate docs
rm -rf docs/schema_markdown/**/*.md # delete everything first, fresh start
npm run generate-docs && git add docs/schema_markdown
```

### Environment:
MacOS 12.16, Node 16.16, npm 9.6.4

### Anything else we need to know?

Follow-up on #422

### PR DESCRIPTION
**Pull request by JSv4**
#### What type of PR is this?

/kind bug

#### What this PR does / why we need it:

As flagged in #430, doc generator is writing "Compatibility Wrapper" object docs written to wrong part of tree.

It appears the cause of the issue was improper overriding of `SchemaNode` `.directory()` function in `BackwardsCompatibleObjectSchemaNode.ts`, but I am running into an issue getting test suite to run under Windows (see issue #517) and am going to run the action here to check there are no other ill-effects. 

#### Which issue(s) this PR fixes:

Fixes #430

### CODE REVIEW

File: utils/generate-docs/Schema/SchemaNode/Factory.ts [hunk 1]
```diff
@@ -13,7 +13,6 @@ import TypePatternSchemaNode, {
   TypePatternSchemaNodeJson,
 } from "./TypePattern.js";
 export { default as SchemaNode } from "./SchemaNode.js";
-import { repo_raw_url_root } from "../../../schema-utils/Constants.js";
```
Comment (JSv4) [inline utils/generate-docs/Schema/SchemaNode/Factory.ts:16]: This wasn't used, and I'd like to stop using these constants.

File: utils/generate-docs/Schema/SchemaNode/BackwardsCompatibleObjectSchemaNode.ts [hunk 2]
```diff
@@ -41,9 +40,6 @@ export default class BackwardsCompatibleObjectSchemaNode extends SchemaNode {
 
   protected basename = () => path.basename(this.id(), ".schema.json");
 
-  protected directory = () =>
```
Comment (JSv4) [inline utils/generate-docs/Schema/SchemaNode/BackwardsCompatibleObjectSchemaNode.ts:44]: This is what's creating the undesired path that is being written to during document generation for the Compatibility Wrappers.

**Comment by JSv4** [comment]
@jacobyavis, @pjohnmeyer, this seems to have solved the issue without changing anything else in the MD. Can you confirm?

**Review by jacobyavis — APPROVED** [review]
Makes sense, nice job!
